### ISSUE TITLE
what  “--mod <path_to_module>” means in chronos

### ISSUE THREAD

**Issue by ChenhuaYang** [amit-davidson/Chronos#44]
My project structure is:
```text
- main
    - main.go
```
And in `main.go`, I copied code from chronos testdata:
```go
package main

type A struct {
	X int
}

func main() {
	a := A{}
	go func() {
		a.X = 1
	}()
	a.X = 2
}
```

But when I tried the args :
```
--file <path to project>\main\main.go --mod <path to project>\main
```

The output is `No data races found`
What's wrong?  And what's mod in chronos?
Thanks.

**Comment by amit-davidson** [comment]
`--mod` means module. It is used to tell Chronos what package to run on and what packages to skip. So you would probably want to find race conditions only in the packages inside your module and skip `stdlib` or external packages. 

As for the `No data races found`, it's not best, but you should add `\` at the end of the command like this:  
```
--file <path to project>\main\main.go --mod <path to project>\main
```
This way, it detects the correct folder. I can't say I did this part in the best way...

**Comment by ChenhuaYang** [comment]
Thanks Amit.  In my opinion, if one user tell chronos which file to detect, they also tell chronos the module. One main file has  one corresponding module, is it right? By the way, if one user give chronos only a module path or an arbitrary folder contains a main file, chronos should also found the main file and the corresponding module to detect race condition.

**Comment by amit-davidson** [comment]
About detecting the module using the main file. That's sounds right. I think you could go up the folder tree until you found the closest go.mod/go.sun and declare it as the module.
About detecting the main file using the module, so that's not correct because a module might have more than one main file if there are many executables.
So theoretically, providing only a main file should be enough, but not the other way around.

**Comment by ChenhuaYang** [comment]
Thanks Amit! I am new to Golang.

**Comment by amit-davidson** [comment]
Happy to help!
